version: '2'
services:
  virtuoso:
    image: aokinobu/virtuoso:v7.2.4.2
    ports:
      - 1111:1111
      - 8890:8890
    volumes:
      - ${HOME}/${SITE_CODE}/virtuoso/data:/virtuoso
      - /etc/localtime:/etc/localtime
      - /usr/local/virtuoso-opensource/bin
    restart: always
