version: '3.4'
services:
  virtuoso:
    build: .
    image: aokinobu/virtuoso:v7.2.4.2
    ports:
      - 1111:1111
      - 8890:8890
    volumes:
      - ${HOME}/${SITE_CODE}/virtuoso/data:/usr/local/virtuoso-opensource/var/lib/virtuoso
# macosx cannot handle this
#      - /etc/localtime:/etc/localtime
    restart: always
