version: '3.4'
services:
  virtuoso:
    build: .
    image: aokinobu/virtuoso:v7.2.4.2
    ports:
      - 1111:1111
      - 8890:8890
    volumes:
      - ${HOME}/${SITE_CODE}/virtuoso/data:/virtuoso
      - /etc/localtime:/etc/localtime
    environment:
      - VIRTUAL_HOST=${VIRTUOSO_VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUOSO_VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${VIRTUOSO_VIRTUAL_HOST}
      - LETSENCRYPT_PORT=${VIRTUOSO_VIRTUAL_PORT}
      - LETSENCRYPT_EMAIL=${SITE_EMAIL}
    restart: always
